# E12. Exception Handling

## 12.1 예외 처리하기

- 예외 처리(exception handling): 예외가 발생하였을 때, 파이썬이 아니라 프로그래머가 작성한 코드로 발생한 오류를 처리하는 것

```python
try:
    실행할 코드
except:
    예외가 발생했을 때 처리할 코드
```



```python
# FileNotFoundError 처리하기
import os

try:
    os.remove('파일명')
except:
    print('파일이 없습니다')
```



```python
# ZeroDivisionError: division by zero 처리하기

try:
    x = int(input('나눌 숫자를 입력하세요'))
    y = 10 / x
    print(y)
except:
    print('0으로 나눌 수 없습니다')
```



```python
# ValueError: substring not found 처리하기
myStr = '파이썬 파이썬 파이썬'
strPosList = []
index = 0

while True:
    try:
        index = myStr.index('파이썬', index)
        strPosList.append(index)
        index += 1
    except:
        break

print('파이썬 글자 위치 -->', strPosList)
```



## 12.2 특정 예외 처리하기

```python
try:
    실행 문장들
except 예외종류1:
    해당 에외를 처리할 코드1
except 예외종류2
    해당 에외를 처리할 코드2
```

- `except` 뒤에 아무것도 명시하지 않으면 모든 종류의 예외를 처리



### 12.2.1 대표적인 예외의 종류

| 예외                | 발생하는 경우                                                |
| ------------------- | ------------------------------------------------------------ |
| `ImportError`       | `import` 문에서 오류가 발생할 때                             |
| `IndexError`        | index의 범위를 벗어났을 때                                   |
| `KeyError`          | 딕셔너리에서 키가 없을 때                                    |
| `KeyboardInterrupt` | 프로그램 실행 중 ctrl + c 누를 때                            |
| `NameError`         | 선언되지 않은 변수에 접근할 때                               |
| `RecursionError`    | 재귀 호출의 횟수가 1000번을 넘을 때                          |
| `RuntimeError`      | 실행 도중 예외 발생                                          |
| `SyntaxError`       | `exec()`나 `eval()`에서 문법 상 오류가 발생할 때             |
| `TypeError`         | 타입 에러가 발생할 때(예: `문자열 - 문자열` 연산)            |
| `ValueError`        | 함수의 매개변수에 잘못된 값을 넘길 경우(예: `int('파이썬')`) |
| `ZeroDivisionError` | 0으로 나눌 때                                                |
| `IOError`           | 파일 처리 등의 오류가 발생할 때                              |



```python
# 리스트의 인덱스와 divisor를 받아 해당 인덱스의 요소를 divisor로 나누기
y = [10, 20, 30]

try:
    index, x = map(int, input('인덱스와 나눌 숫자를 입력하세요: ').split())
    print(y[index] / x)
except ZeroDivisionError:
    print('숫자를 0으로 나눌 수 없습니다')
except IndexError:
    print('잘못된 인덱스입니다')
```



```python
# 두 수를 입력받아 후자로 전자 나누기
num1 = input('숫자1-->')
num2 = input('숫자2-->')

try:
    num1 = int(num1)
    num2 = int(num2)
    
    while True:
        res = num1/num2
        
except ValueError:
    print('문자열은 숫자로 변환할 수 없다')
    
except ZeroDivisionError:
    print('0으로 나눌 수 없다')
    
except KeyboardInterrupt:
    print('ctrl+c 눌림')
```



### 12.3 예외 메시지 받아오기

```python
try:
    실행할 코드
except 예외 as 변수:
    예외 발생했을 때 처리하는 코드
```



```python
y = [10, 20, 30]

try:
    index, x = map(int, input('인덱스와 나눌 숫자를 입력하세요: ').split())
    print(y[index] / x)
except ZeroDivisionError as e:
    print('숫자를 0으로 나눌 수 없습니다', e)
except IndexError as e:
    print('잘못된 인덱스입니다', e)
```

```python
인덱스와 나눌 숫자를 입력하세요: 2 0
숫자를 0으로 나눌 수 없습니다 division by zero
```

- 예외가 여러 개 발생하여도 먼저 발생한 예외의 처리 코드만 실행된다.

```python
except Exception as e:
    print('예외가 발생했습니다', e)
```

- 모든 종류의 예외를 처리하려면 `Exception`으로 지정한다.



## 12.4 else문 사용하기

```python
try:
    실행할 코드
except:
    예외 처리 코드
else:
    예외 발생하지 않았을 때 실행할 코드
```

- `try`문에서 오류가 발생하면 `except`문을 실행
- `try`문에서 오류가 발생하지 않으면 `else`문을 실행
- `else`문은 `except`문 뒤에 오며, `else`문을 사용하면 `except`문을 생략할 수 없다.



```python
# 입력한 숫자로 10을 나누고 예외 발생하지 않을 경우 결과 출력하기
try:
    x = int(input('나눌 숫자를 입력하세요'))
    y = 10 / x
except zeroDivisionError:
    print('숫자를 0으로 나눌 수 없습니다')
else:
    print('나눗셈 결과: ', y)
```



## 12.5 finllay문 사용하기

```python
try:
    실행할 코드
except:
    예외 처리 코드
else:
    예외 발생하지 않았을 때 실행할 코드
finally:
    예외 발생 여부와 상관없이 실행할 코드
```

- `finally`문은 `except`문과 `else`문을 생략해도 사용 가능
- `finally`문: 예외가 발생하건, 발생하지 않건 무조건 코드를 실행한다.



```python
# finllay 사용하기
try:
    x = int(input('나눌 숫자를 입력하세요'))
    y = 10 / x
except zeroDivisionError:
    print('숫자를 0으로 나눌 수 없습니다')
else:
    print('나눗셈 결과: ', y)
finally:
    print('코드 실행이 끝났습니다')
```

